#include "draw.h"
#include "gba.h"
#include "startimage.h"
#include "ingamebackground.h"
#include "frog.h"
#include "bigtruck.h"
#include "purplecar.h"
#include "bulldozer.h"
#include "racecar.h"
#include "yellowcar.h"
#include "gameover.h"
#include "winscreen.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawFullScreenImageDMA(ingamebackground);

    drawFrog(state->frogrow, state->frogcol, 11, 13, froggerfrog);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    int row = state->frogrow;
    int col = state->frogcol;
    int truckcol = state->truckcolumn;
    int carcol = state->purplecarcolumn;
    int bullcol = state->bulldozercolumn;
    int racecol = state->racecarcolumn;
    int yellowcol = state->yellowcarcolumn;

    drawRectDMA(4, 63, 8, 6, BLACK);	//This undraws the previous life counter
    drawRectDMA(row, col, 11, 13, BLACK);	//This undraws the frog
    drawRectDMA(128, truckcol, 38, 12, BLACK);
    drawRectDMA(80, carcol, 14, 12, BLACK);
    drawRectDMA(105, bullcol, 20, 14, BLACK);
    drawRectDMA(65, racecol, 14, 12, BLACK);
    drawRectDMA(42, yellowcol, 15, 17, BLACK);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    int row = state->frogrow;
    int col = state->frogcol;    

    int truckcol = state->truckcolumn;
    int bullcol = state->bulldozercolumn;
    int racecol = state->racecarcolumn;
    int carcol = state->purplecarcolumn;
    int yellowcol = state->yellowcarcolumn;


    drawChar(63, 4, state->lives+48, WHITE);

    drawCar(BigTruck, 38, 12, 128, truckcol);

    drawCar(purplecar, 14, 12, 80, carcol);

    drawCar(bulldozer, 20, 14, 105, bullcol);

    drawCar(racecar, 14, 12, 65, racecol);

    drawCar(yellowcar, 15, 17, 42, yellowcol);

    drawFrog(row, col, 11, 13, froggerfrog);

}

void drawFrog(int r, int c, int width, int height, const unsigned short *image) {
	drawImageDMA(r, c, width, height, image);
}

void drawCar(const u16 *image, int width, int height, int row, int column){
	drawImageDMA(row, column, width, height, image);
}
